### ISSUE TITLE
Policy to set maximum content size and other constraints

### ISSUE THREAD

**Issue by jkarlin** [igrigorik/feature-policy#21]
It would be nice to be able to restrict content size of frames with the same API as it would require all of the same mechanisms. But it's not a feature and it requires an argument. So it's a bit of an awkward fit. How about a new "constraint" directive, like so:

```javascript
Feature-Policy: {"constraint": {"max-content-size": 500000}, "target": ["https://example.com"]}
```

Other possible constraints include:

- max time to load a frame or resource before aborting
- max content size of various resource types
- max number of requests (again, maybe break down by type)

**Comment by ojanvafai** [comment]
What's the advantage of using the same header for resource sizes? We could use the same syntax, but a different header.

The reason to keep it separate is we want feature policy to be just about enabling/disabling features, not changing the behavior of features in subtle ways. If we include size constraints in this API, it's hard to reason about what APIs make sense to restrict via this API.

**Comment by jkarlin** [comment]
If it's just about enabling/disabling features then I completely agree that it should be a separate header.
