### ISSUE TITLE
Spec "Trials Policy" to expose experimental features to specific origin (Origin Trials)

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/feature-policy#8]
- Origin Trials Framework: https://www.chromestatus.com/feature/6331324939894784
- Explainer: https://github.com/jpchase/OriginTrials/blob/gh-pages/explainer.md

> Implement a framework for exposing experimental features in the browser, but only to specific/registered origins, for limited duration and subject to global usage caps.

In effect, it's the opposite of the "[Disable Policy](https://igrigorik.github.io/feature-policy/#disable-policy)". We should be able to share the same infrastructure, e.g..

```
Feature-Policy: {"trial":["token1", "token2"]}, {"disable":["webrtc","geolocation"]}
```

As far as FP is concerned, "trial policy" is a list of opaque tokens: we parse them out and we expose them, but we don't act on them... Other specs can hook in and run their own logic on said policy. 

A "trial policy" has the following properties:
 1. `mode` is always set to `enforce`
 - `target` is always set to `self`
 - `report-to` is always set to _null_
  - or, we just refactor to avoid 1-3 for trial policies altogether..
 - is not advertised on subrequests and does not need to be reflected back.

~ish? /cc @mikewest @jpchase

**Comment by jpchase** [comment]
Adding @clelland

**Comment by igrigorik** [comment]
See https://github.com/igrigorik/feature-policy/issues/9 for a sketch proposal.

**Comment by igrigorik** [comment]
Closing this, let's track progress in https://github.com/igrigorik/feature-policy/issues/9 / https://github.com/igrigorik/feature-policy/issues/17.
